#!/bin/bash

projectsFile=${HOME}"/dev/utilities/commands/projects.json"

declare -A projects
while IFS="=" read -r key value
do
    projects[$key]="$value"
done < <(jq -r "to_entries|map(\"\(.key)=\(.value)\")|.[]" ${projectsFile})

if [ $# -eq 0 ]; then
	echo List of projects available:
	for project in "${!projects[@]}"; do
		echo $project: ${projects[$project]};
	done;
elif [[ -n ${projects[$1]} ]]; then	
	path=${projects[$1]//[~]/${HOME}}
        eval cd ${path}
	exec /bin/zsh;
else
	echo Unknown project
fi
