#!/bin/bash

projectsFile=${HOME}"/dev/utilities/commands/projects.json"

declare -A projects
while IFS="=" read -r key value
do
    projects[$key]="$value"
done < <(jq -r "to_entries|map(\"\(.key)=\(.value)\")|.[]" ${projectsFile})

if [ -n $1 ]; then
        path=${projects[$1]//[~]/${HOME}}
        eval cd ${path}
        exec /bin/zsh
fi
